#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

nuke-main-cmd() {
  declare desc="close all ports belonging to the app"
  local cmd="nuke"
  [[ "$1" == "$cmd" ]] && shift 1
  local CONTAINERS IMAGES RUNNING_CONTAINERS

  RUNNING_CONTAINERS=$(docker ps -q | tr '\n' ' ')
  if [[ -n "$RUNNING_CONTAINERS" ]]; then
    dokku_log_info1_quiet "Stopping all containers"
    docker stop $RUNNING_CONTAINERS
  else
    dokku_log_verbose_quiet "No running containers"
  fi

  CONTAINERS=$(docker ps -q -a | tr '\n' ' ')
  if [[ -n "$CONTAINERS" ]]; then
    dokku_log_info1_quiet "Deleting all stopped containers"
    docker rm -f $CONTAINERS
  else
    dokku_log_verbose_quiet "No containers"
  fi

  IMAGES=$(docker images -a -q | tr '\n' ' ')
  if [[ -n "$IMAGES" ]]; then
    dokku_log_info1_quiet "Deleting all images"
    docker rmi $IMAGES
  else
    dokku_log_verbose_quiet "No images"
  fi
}

nuke-main-cmd "$@"
